### ISSUE TITLE
digitalRead(pin_pcb_ok)) is always TRUE

### ISSUE THREAD

**Issue by floresboy** [Juerd/operame#3]
The:
const int       pin_pcb_ok       = 12;   // pulled to GND by PCB trace
while (digitalRead(pin_pcb_ok)) {
        display_big("module verkeerd om", TFT_RED);
}

always results in a TRUE so the init stalls at this point. Connections seem OK but with no schematics  its hard to check everything.

- Would it be possible to add scematics (with coresponding pin numbers ( pin_pcb_ok / 12). 
- is 2250 a reasanoble value is is the sensor faulty after all? 

Thanks, Kamiel

**Comment by Juerd** [comment]
floresboy skribis 2021-01-02 13:18 (-0800):
>   The:
> const int       pin_pcb_ok       = 12;   // pulled to GND by PCB trace
> while (digitalRead(pin_pcb_ok)) {
>         display_big("module verkeerd om", TFT_RED);
> }
> always results in a TRUE so the init stalls at this point. Connections
> seem OK but with no schematics its hard to check everything.
> Would it be possible to add scematics (with coresponding pin numbers ( pin_pcb_ok / 12). 

Have you read https://operame.nl/index.php/Hardware?

Basically, pin 12 has to be pulled to GND, as is also in the comment.

The pcb designer is busy with other things but will upload the kicad
files soon. But regarding the schematic, it's just 4 traces and a ground
plane.

> is 2250 a reasanoble value is is the sensor fault after all? 

It is, but if the sensor has calibrated well, 2250 means your
ventilation is abysmal :)

Regarding calibration:
https://operame.nl/index.php/Gebruikershandleiding#Eerste_gebruik


Regards,

Juerd
Operame

**Comment by floresboy** [comment]
Thanks, seems to be bad solder joint, Was 200 mV difference betreen pin 12 and Power GND. That was enough to asses signal as HIGH. Resoldered and open my shed door. Both problems solved ! Thanks again, K
