### ISSUE TITLE
Add support for MQTT Discovery

### ISSUE THREAD

**Issue by fantpmas** [Juerd/operame#8]
To be able to easily add the sensor to systems like Home Assistant, [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/) would be handy.

**Comment by Juerd** [comment]
Perhaps, but I have no interest in writing support for that, and fear that implementing this adds non-trivial complexity to the code, which would go against the KISS principle. But if you want to write a clean PR to show me it's just a few lines of code and there's not much that could go wrong, feel free to do so.
